runtime: python312
entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"
  SECRET_KEY: "d227addc85484c989b51c42632d6b2d1a5d3b5a9c8a7b6b5a4d3c2b1a0987654"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
