runtime: python39
entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
