runtime: python312
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
